# Generated by Django 3.2.6 on 2021-08-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_ami_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='ami',
            name='gif',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
