# Generated by Django 3.2.6 on 2021-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ami_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='ami',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
