# Generated by Django 3.2.6 on 2021-08-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_ami_num_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ami',
            name='is_save',
            field=models.BooleanField(default=False),
        ),
    ]
