# Generated by Django 3.2.6 on 2021-08-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_groupe_is_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='photos_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
