# Generated by Django 3.2.6 on 2021-08-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ami_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ami',
            name='gif',
        ),
    ]
