# Generated by Django 3.2.6 on 2021-08-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_ami_num_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ami',
            name='num_scan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
