# Generated by Django 3.2.6 on 2021-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_ami_num_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ami',
            name='num_scan',
            field=models.IntegerField(default=0),
        ),
    ]
