# Generated by Django 3.2.6 on 2021-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_ami_is_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='is_save',
            field=models.BooleanField(default=False),
        ),
    ]
